// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKRDfeStEUaZRGYuuF86ybhohcFobXiH0',
    appId: '1:846063310661:web:39c644009524d4e24c502c',
    messagingSenderId: '846063310661',
    projectId: 'sample-764a0',
    authDomain: 'sample-764a0.firebaseapp.com',
    storageBucket: 'sample-764a0.firebasestorage.app',
    measurementId: 'G-LYWML4D2CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKhe-42LBtRMbWOjTgVWSy1KDo35nojSk',
    appId: '1:846063310661:android:653c60192167a1664c502c',
    messagingSenderId: '846063310661',
    projectId: 'sample-764a0',
    storageBucket: 'sample-764a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDjqMkBUY-TDlh0ZADFQCCLDaUNnLwLig',
    appId: '1:846063310661:ios:2056eb0b1c029a924c502c',
    messagingSenderId: '846063310661',
    projectId: 'sample-764a0',
    storageBucket: 'sample-764a0.firebasestorage.app',
    iosBundleId: 'com.example.ticketingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDjqMkBUY-TDlh0ZADFQCCLDaUNnLwLig',
    appId: '1:846063310661:ios:2056eb0b1c029a924c502c',
    messagingSenderId: '846063310661',
    projectId: 'sample-764a0',
    storageBucket: 'sample-764a0.firebasestorage.app',
    iosBundleId: 'com.example.ticketingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKRDfeStEUaZRGYuuF86ybhohcFobXiH0',
    appId: '1:846063310661:web:d514d32a01cee5eb4c502c',
    messagingSenderId: '846063310661',
    projectId: 'sample-764a0',
    authDomain: 'sample-764a0.firebaseapp.com',
    storageBucket: 'sample-764a0.firebasestorage.app',
    measurementId: 'G-52TC47E0NL',
  );
}
